external-dns:
  fullnameOverride: adguard-dns
  env:
    - name: DOMAIN_FILTER
      valueFrom:
        secretKeyRef:
          name: adguard-dns-secret
          key: ADGUARD_DOMAIN_FILTER
  extraArgs:
    - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
    - --crd-source-kind=DNSEndpoint
    - --gateway-name=envoy-internal
    - --domain-filter=$(DOMAIN_FILTER)
    - --annotation-filter=external-dns.alpha.kubernetes.io/controller in (internal,dns-controller)
  logLevel: debug
  triggerLoopOnEvent: true
  policy: sync
  sources: ["crd", "gateway-httproute"]
  txtPrefix: k8s.main.
  txtOwnerId: main
  serviceMonitor:
    enabled: true
  provider:
    name: webhook
    webhook:
      image:
        repository: ghcr.io/muhlba91/external-dns-provider-adguard
        tag: v11.0.2@sha256:162561ce7af084ee736a4c62c0bd3c0f12a3842d0ca8d96ac3665c15ef05add8
      service:
        port: 8888
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8080
        initialDelaySeconds: 10
        timeoutSeconds: 5
      readinessProbe:
        httpGet:
          path: /healthz
          port: 8080
        initialDelaySeconds: 10
        timeoutSeconds: 5
      env:
        - name: ADGUARD_URL
          valueFrom:
            secretKeyRef:
              name: adguard-dns-secret
              key: ADGUARD_URL
        - name: ADGUARD_USER
          valueFrom:
            secretKeyRef:
              name: adguard-dns-secret
              key: ADGUARD_USER
        - name: ADGUARD_PASSWORD
          valueFrom:
            secretKeyRef:
              name: adguard-dns-secret
              key: ADGUARD_PASSWORD
        - name: LOG_LEVEL
          value: debug
        - name: DRY_RUN
          value: "false"
