global:
  additionalLabels: {}
  imageRegistry: ""
image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/linuxserver/jellyfin
  tag: 10.11.6@sha256:aae645d1ff11c42b1d2d3b80694e34e0e1ea4a51879900843c8ab6e8b127a32a
jellyfin:
  annotations: {}
  replicaCount: 1
  env:
    - name: TZ
      value: CET
    - name: PUID
      value: "1001"
    - name: PGID
      value: "1001"
    - name: JELLYFIN_PublishedServerUrl
      value: 192.168.48.22
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  service:
    ip: 192.168.48.22
persistence:
  config:
    enabled: true
    accessMode: ReadWriteOnce
    size: 5Gi
    storageClass: ceph-block
  extraNfsMounts:
    - name: tv-shows
      mountPath: /data/tvshows
      nfsPath: /tv-series
      nfsServer: qnap.<secret:private-domain>
      readOnly: false
    - name: movies
      mountPath: /data/movies
      nfsPath: /movies
      nfsServer: qnap.<secret:private-domain>
      readOnly: false
resources:
  requests:
    gpu.intel.com/i915: 1
    cpu: 100m
    memory: 1000Mi
  limits:
    gpu.intel.com/i915: 1
    memory: 6000Mi
nodeSelector: {}
tolerations: []
affinity: {}
