- enabled: "true"
  namespace: adguard-home
  syncWave: "-3"
  syncPolicy:
    enabled: true
    selfHeal: true
    prune: false
  plugin:
    env:
      - name: SECRET_PROVIDER
        value: cluster-secrets
