external-dns:
  fullnameOverride: cloudflare-dns
  provider: cloudflare
  env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: cloudflare-dns-secret
          key: CF_API_TOKEN
    - name: CF_ZONE_ID
      valueFrom:
        secretKeyRef:
          name: cloudflare-dns-secret
          key: CF_ZONE_ID
  extraArgs:
    - --cloudflare-dns-records-per-page=1000
    - --cloudflare-proxied
    - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
    - --crd-source-kind=DNSEndpoint
    - --gateway-name=envoy-external
    - --zone-id-filter=$(CF_ZONE_ID)
  triggerLoopOnEvent: true
  policy: sync
  sources: ["crd", "gateway-httproute"]
  txtPrefix: k8s.
  txtOwnerId: default
  domainFilters: ["${SECRET_DOMAIN}"]
  serviceMonitor:
    enabled: true
