external-dns:
  fullnameOverride: cloudflare-dns
  provider: cloudflare
  env:
    - name: &name CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: &secret cloudflare-dns-secret
          key: *name
    - name: &name CF_ZONE_ID
      valueFrom:
        secretKeyRef:
          name: *secret
          key: *name
    - name: &name CF_DOMAIN_FILTER
      valueFrom:
        secretKeyRef:
          name: *secret
          key: *name
  extraArgs:
    - --cloudflare-dns-records-per-page=1000
    - --cloudflare-proxied
    - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
    - --crd-source-kind=DNSEndpoint
    - --gateway-name=envoy-external
    - --zone-id-filter=$(CF_ZONE_ID)
    - --domain-filter=$(CF_DOMAIN_FILTER)
  triggerLoopOnEvent: true
  policy: sync
  sources: ["crd", "gateway-httproute"]
  txtPrefix: k8s.
  txtOwnerId: default
  serviceMonitor:
    enabled: true
