apiVersion: v2
name: coder
type: application
version: 1.0.0
dependencies:
  - name: coder
    version: 2.37.0
    repository: https://helm.coder.com/v2
  - name: pgsql-cnpg
    version: 1.4.0
    repository: file://../../../../charts/pgsql-cnpg/
