apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bookorbit-secrets
  namespace: bookorbit
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  refreshInterval: 1h
  target:
    name: bookorbit-secrets
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: "b41d487b-9f6b-4b56-afc2-b45e00b1b5a4" #gitleaks:allow #BOOKORBIT_JWT_SECRET
    - secretKey: SETUP_BOOTSTRAP_TOKEN
      remoteRef:
        key: "88776bb5-2c08-4d17-8dbe-b45e00b1c713" #gitleaks:allow #BOOKORBIT_SETUP_BOOTSTRAP_TOKEN
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        key: "cfe75c77-d0cf-45c9-9656-b45e00b21a3b" #gitleaks:allow #BOOKORBIT_OIDC_CLIENT_ID
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: "6a4e4407-2d07-461b-9dce-b45e00b21193" #gitleaks:allow #BOOKORBIT_OIDC_CLIENT_SECRET
    - secretKey: OIDC_ISSUER_URL
      remoteRef:
        key: "32bc5994-ce57-4964-9c3a-b45e00b293b1" #gitleaks:allow #BOOKORBIT_OIDC_ISSUER_URL
    - secretKey: S3_ACCESS_KEY_ID
      remoteRef:
        key: "e00e1e38-ae37-479a-8b46-b409016331eb" #gitleaks:allow #S3_ACCESS_KEY
    - secretKey: S3_ACCESS_SECRET_KEY
      remoteRef:
        key: "4d5a418c-82ed-4b8e-bfbf-b40901634ea4" #gitleaks:allow #S3_SECRET_KEY
