apiVersion: v1
kind: PersistentVolume
metadata:
  name: bookorbit-ebooks-pv
spec:
  storageClassName: ebooks
  claimRef:
    name: bookorbit-ebooks-pvc
    namespace: bookorbit
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: qnap.<secret:private-domain>
    path: "/ebooks"
  mountOptions:
    - nfsvers=4.1
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookorbit-ebooks-pvc
  namespace: bookorbit
spec:
  volumeName: bookorbit-ebooks-pv
  storageClassName: nfs-qnap
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
