open-webui:
  ollama:
    enabled: false
  ingress:
    enabled: true
    class: "traefik"
    host: chat.<secret:private-domain>
    tls: true
  image:
    repository: ghcr.io/open-webui/open-webui
    tag: "v0.6.10@sha256:e62f0bd1fe2901f838c4dea7d26d2332b2845da2a09a8c3ed99655db7bcbe4f5"
    pullPolicy: "IfNotPresent"
  websocket:
    enabled: false
