open-webui:
  ollama:
    enabled: false
  ingress:
    enabled: true
    class: "traefik"
    host: chat.<secret:private-domain>
    tls: true
  image:
    repository: ghcr.io/open-webui/open-webui
    tag: "0.6.1@sha256:d8d83bd266bc5c3810d89a0402f541065de5f9b650167a27db5288ec5ffad68e"
    pullPolicy: "IfNotPresent"
  websocket:
    enabled: false
