apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  refreshInterval: 1h
  target:
    name: litellm-secrets
    creationPolicy: Owner
  data:
    - secretKey: S3_ACCESS_KEY_ID
      remoteRef:
        key: "e00e1e38-ae37-479a-8b46-b409016331eb" #gitleaks:allow #S3_ACCESS_KEY
    - secretKey: S3_ACCESS_SECRET_KEY
      remoteRef:
        key: "4d5a418c-82ed-4b8e-bfbf-b40901634ea4" #gitleaks:allow #S3_SECRET_KEY
    - secretKey: ANTHROPIC_API_KEY
      remoteRef:
        key: "b4f5ae0d-6b2e-44bc-85ee-b409016935b1" #gitleaks:allow #LITELLM_ANTHROPIC_API_KEY
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: "4c81f1cb-f3dd-4077-a66e-b409016956fc" #gitleaks:allow #LITELLM_OPENAI_API_KEY
    - secretKey: LITELLM_MASTER_KEY
      remoteRef:
        key: "1eb6b1b9-7dbe-4e6c-8d31-b40901588b8f" #gitleaks:allow #LITELLM_MASTER_KEY
