apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: anytype-coordinator-config
  namespace: anytype
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  refreshInterval: 1h
  target:
    name: anytype-coordinator-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config.yml: '{{`{{ .COORDINATOR_CONFIG }}`}}'
        network.yml: '{{`{{ .NETWORK_CONFIG }}`}}'
  data:
    - secretKey: COORDINATOR_CONFIG
      remoteRef:
        key: "85683096-2902-4a68-ad83-b471016797bf" #gitleaks:allow #anytype-coordinator-config
    - secretKey: NETWORK_CONFIG
      remoteRef:
        key: "9a83d575-b6a1-4c25-9716-b4710167c319" #gitleaks:allow #anytype-network-config
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: anytype-consensus-config
  namespace: anytype
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  refreshInterval: 1h
  target:
    name: anytype-consensus-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config.yml: '{{`{{ .CONSENSUS_CONFIG }}`}}'
  data:
    - secretKey: CONSENSUS_CONFIG
      remoteRef:
        key: "bcbcfad3-9407-49db-9701-b4710167f96f" #gitleaks:allow #anytype-consensus-config
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: anytype-syncnode-config
  namespace: anytype
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  refreshInterval: 1h
  target:
    name: anytype-syncnode-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config.yml: '{{`{{ .SYNCNODE_CONFIG }}`}}'
  data:
    - secretKey: SYNCNODE_CONFIG
      remoteRef:
        key: "967b40f9-d643-4859-8ad6-b47101683193" #gitleaks:allow #anytype-syncnode-config
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: anytype-filenode-config
  namespace: anytype
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  refreshInterval: 1h
  target:
    name: anytype-filenode-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config.yml: '{{`{{ .FILENODE_CONFIG }}`}}'
  data:
    - secretKey: FILENODE_CONFIG
      remoteRef:
        key: "26b692b6-e09c-448b-80ca-b471016862f3" #gitleaks:allow #anytype-filenode-config
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: anytype-aws-credentials
  namespace: anytype
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  refreshInterval: 1h
  target:
    name: anytype-aws-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        credentials: |
          [default]
          aws_access_key_id={{`{{ .AWS_ACCESS_KEY_ID }}`}}
          aws_secret_access_key={{`{{ .AWS_SECRET_ACCESS_KEY }}`}}
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: "efd100bb-4c88-4dfd-b602-b4710166f814" #gitleaks:allow #anytype-aws-access-key-id
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: "7b0a78e9-6939-491e-ade6-b471016710e4" #gitleaks:allow #anytype-aws-secret-access-key
