global:
  additionalLabels: {}
  podAnnotations: {}
  podLabels: {}
  image:
    imagePullPolicy: IfNotPresent
server:
  name: server
  replicas: 1
  podAnnotations: {}
  podLabels: {}
  containerPort: 80
  config:
    mode: production
    locale: pl
    currency: PLN
    firstDayOfWeek: 1
    basePath: ""
    baseUrl: "/"
    barcodePlugin: DemoBarcodeLookupPlugin
    # default is `DefaultAuthMiddleware`, reverse proxy is `ReverseProxyAuthMiddleware`
    authClass: ReverseProxyAuthMiddleware
    reverseProxyAuthHeader: x-auth-request-preferred-username
  env:
    - name: PUID
      value: "1000"
    - name: PGID
      value: "1000"
    - name: TZ
      value: CET
  envFrom: []
  image:
    imagePullPolicy: IfNotPresent
    repository: lscr.io/linuxserver/grocy
    tag: 4.6.0@sha256:3734cf765d943120afc9b98ae36ac980bd498d37cd269cd5ad6be3c993ba22a2
  service:
    type: ClusterIP
    servicePortHttpName: http
    servicePortHttp: 80
    namedTargetPort: true
  ingresses: []
  readinessProbe:
    enabled: false
    failureThreshold: 5
    initialDelaySeconds: 30
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 2
  livenessProbe:
    enabled: false
    failureThreshold: 5
    initialDelaySeconds: 30
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 2
  resources: {}
persistance:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
