apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: daytonadb-init-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  refreshInterval: 1h
  target:
    name: daytonadb-init-secret
    creationPolicy: Owner
    template:
      data:
        username: app
  data:
    - secretKey: password
      remoteRef:
        key: "c198e0e6-e255-41a3-89f1-b45d00ebd7f1" #gitleaks:allow #DAYTONA_DB_PASSWORD
