apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: doppler-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  refreshInterval: 1h
  target:
    name: doppler-token-auth-api
    creationPolicy: Owner
  data:
    - secretKey: dopplerToken
      remoteRef:
        key: "9a439756-660e-4d50-8af8-b40a00968312" #gitleaks:allow #DOPPLER_TOKEN
---
apiVersion: v1
kind: Secret
metadata:
  name: bitwarden-access-token
type: Opaque
data:
  bw-token: ""
