{{- range .Values.nfsMounts }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-{{ .name }}
spec:
  claimRef:
    name: jellyfin-{{ .name }}
    namespace: jellyfin
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: {{ .nfsServer }}
    path: {{ .nfsPath | quote }}
  mountOptions:
    - nfsvers=4.1
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-{{ .name }}
  namespace: jellyfin
spec:
  volumeName: jellyfin-{{ .name }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
{{- end }}
