#!/usr/bin/env bash
echo "# This manifest was generated by automation. DO NOT EDIT." > ./provision/talos/manifests/kubelet-csr-approver/kubelet-csr-approver.yaml
helm dependency update ./cluster/system/kubelet-csr-approver
helm template kubelet-csr-approver ./cluster/system/kubelet-csr-approver --namespace kube-system >> ./provision/talos/manifests/kubelet-csr-approver/kubelet-csr-approver.yaml
