apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-dns
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: cloudflare-dns-secret
    template:
      data:
        CF_API_TOKEN: "{{ .CLOUDFLARE_DNS_TOKEN }}"
        CF_ZONE_ID: "{{ .CLOUDFLARE_ZONE_ID }}"
        CF_DOMAIN_FILTER: "{{ .CLOUDFLARE_DOMAIN_FILTER }}"
  data:
  - secretKey: CLOUDFLARE_DNS_TOKEN
    remoteRef:
      key: "replace-CLOUDFLARE_DNS_TOKEN" #CLOUDFLARE_DNS_TOKEN
  - secretKey: CLOUDFLARE_ZONE_ID
    remoteRef:
      key: "replace-CLOUDFLARE_ZONE_ID" #CLOUDFLARE_ZONE_ID
  - secretKey: CLOUDFLARE_DOMAIN_FILTER
    remoteRef:
      key: "replace-CLOUDFLARE_DOMAIN_FILTER" #CLOUDFLARE_DOMAIN_FILTER
