apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-dns
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: cloudflare-dns-secret
    template:
      data:
        CF_API_TOKEN: '{{ `{{ .CLOUDFLARE_DNS_TOKEN }}` }}'
        CF_ZONE_ID: '{{ `{{ .CLOUDFLARE_ZONE_ID }}` }}'
        CF_DOMAIN_FILTER: '{{ `{{ .CLOUDFLARE_DOMAIN_FILTER }}` }}'
  data:
  - secretKey: CLOUDFLARE_DNS_TOKEN
    remoteRef:
      key: "6ee8fbcd-0d83-46e4-bb3a-b4070113b8af" #gitleaks:allow #CLOUDFLARE_DNS_TOKEN
  - secretKey: CLOUDFLARE_ZONE_ID
    remoteRef:
      key: "7b0e1762-c2c3-4d2a-b208-b4070114025a" #gitleaks:allow #CLOUDFLARE_ZONE_ID
  - secretKey: CLOUDFLARE_DOMAIN_FILTER
    remoteRef:
      key: "3eb59a75-030c-4e7e-8b96-b4070113a18d" #gitleaks:allow #CLOUDFLARE_DOMAIN_FILTER
