apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: onlyoffice-jwt-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  refreshInterval: 1h
  target:
    name: onlyoffice-jwt-secret
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: "<BITWARDEN_UUID_nextcloud-onlyoffice-jwt-secret>" #gitleaks:allow #ONLYOFFICE_JWT_SECRET
