- enabled: "true"
  appSubfolder: operator
  namespace: rook-ceph
  syncWave: "1"
  syncPolicy:
    enabled: false
    selfHeal: true
    prune: false
  managedNamespaceMetadata:
    labels:
      pod-security.kubernetes.io/enforce: privileged
- enabled: "true"
  appSubfolder: csi-drivers
  namespace: rook-ceph
  syncWave: "2"
  syncPolicy:
    enabled: false
    selfHeal: true
    prune: false
- enabled: "true"
  appSubfolder: cluster
  namespace: rook-ceph
  syncWave: "3"
  syncPolicy:
    enabled: false
    selfHeal: true
    prune: false
  plugin:
    env:
      - name: SECRET_PROVIDER
        value: cluster-secrets
  ignoreDifferences:
    - group: ceph.rook.io
      kind: CephCluster
      jsonPointers:
        - /spec/monitoring/rulesNamespaceOverride
        - /metadata/labels
        - /spec/monitoring/createPrometheusRules
    - group: ceph.rook.io
      kind: CephObjectStore
      jsonPointers:
        - /spec/healthCheck
