apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: rabbitmq-cluster-operator

resources:
  # renovate-raw: datasource=github-releases depName=rabbitmq/cluster-operator
  - https://github.com/rabbitmq/cluster-operator/releases/download/v2.22.4/cluster-operator.yml
