apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: adguard-home
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  refreshInterval: 1h
  target:
    name: adguard-home-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ORIGIN_USERNAME: "{{ `{{ .ADGUARD_USER }}` }}"
        ORIGIN_PASSWORD: "{{ `{{ .ADGUARD_PASSWORD }}` }}"
        REPLICA1_USERNAME: "{{ `{{ .ADGUARD_USER }}` }}"
        REPLICA1_PASSWORD: "{{ `{{ .ADGUARD_PASSWORD }}` }}"
  data:
    - secretKey: ADGUARD_USER
      remoteRef:
        key: "7e657efe-c9fa-420d-8959-b40800e9dea5" #gitleaks:allow #ADGUARD_USER
    - secretKey: ADGUARD_PASSWORD
      remoteRef:
        key: "6ccac8f0-d23e-48da-ae23-b40800e9e7f0" #gitleaks:allow #ADGUARD_PASSWORD
