# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rabbitmq-definitions
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  refreshInterval: 1h
  target:
    name: rabbitmq-definitions
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        definitions.json: |
          {
            "vhosts": [
              {"name": "/"}
            ],
            "users": [
              {"name": "{{ `{{ .admin_username }}` }}", "password": "{{ `{{ .admin_password }}` }}", "tags": ["administrator"]},
              {"name": "{{ `{{ .home_assistant_username }}` }}", "password": "{{ `{{ .home_assistant_password }}` }}", "tags": []}
            ],
            "permissions": [
              {"user": "{{ `{{ .admin_username }}` }}", "vhost": "/", "configure": ".*", "write": ".*", "read": ".*"},
              {"user": "{{ `{{ .home_assistant_username }}` }}", "vhost": "/", "configure": ".*", "write": ".*", "read": ".*"}
            ]
          }
  data:
    - secretKey: admin_username
      remoteRef:
        key: "51a18ec8-bede-48ab-b519-b40a00d706e9" #gitleaks:allow #RABBITMQ_ADMIN_USERNAME (reused from VERNEMQ_ADMIN_USERNAME)
    - secretKey: admin_password
      remoteRef:
        key: "b41c1bad-ee30-4007-99cc-b40a00d72284" #gitleaks:allow #RABBITMQ_ADMIN_PASSWORD (reused from VERNEMQ_ADMIN_PASSWORD)
    - secretKey: home_assistant_username
      remoteRef:
        key: "05543802-765d-45dc-b97a-b40a00d743b1" #gitleaks:allow #RABBITMQ_HOME_ASSISTANT_USERNAME (reused from VERNEMQ_HOME_ASSISTANT_USERNAME)
    - secretKey: home_assistant_password
      remoteRef:
        key: "f872ad0e-cc13-42ec-b3b8-b40a00d76098" #gitleaks:allow #RABBITMQ_HOME_ASSISTANT_PASSWORD (reused from VERNEMQ_HOME_ASSISTANT_PASSWORD)
