apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-server-models
  namespace: llm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.server.storage }}
