---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: discord
  namespace: monitoring
  labels:
    app: kube-prometheus-stack
    release: prometheus-stack
spec:
  route:
    receiver: discord
    groupBy: ['namespace', 'severity']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    matchers:
      - name: severity
        matchType: =~
        value: 'critical|warning'
  receivers:
    - name: discord
      discordConfigs:
        - apiURL:
            name: alertmanager-discord-webhook
            key: url
          title: '{{`{{ if eq (len .Alerts) 1 }}{{ (index .Alerts 0).Annotations.summary }}{{ else }}{{ len .Alerts }} {{ .CommonLabels.severity }} alerts in {{ .CommonLabels.namespace }}{{ end }}`}}'
          message: |-
            {{`{{ if eq .CommonLabels.severity "critical" }}@here {{ end }}{{ range .Alerts }}**{{ .Annotations.summary }}**
            {{ .Annotations.description }}

            {{ end }}`}}
          sendResolved: true
