apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-discord-webhook
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  refreshInterval: 1h
  target:
    name: alertmanager-discord-webhook
    creationPolicy: Owner
  data:
    - secretKey: url
      remoteRef:
        key: "9ac66262-5201-41cd-a8a6-b48d00e3cb06" #gitleaks:allow #ALERTMANAGER_DISCORD_WEBHOOK
