apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hermes-agent-secrets
  namespace: hermes-agent
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  refreshInterval: 1h
  target:
    name: hermes-agent-secrets
    creationPolicy: Owner
  data:
    {{- range .Values.externalSecrets }}
    - secretKey: {{ .secretName }}
      remoteRef:
        key: {{ .bwsId | quote }}
    {{- end }}
