apiVersion: v1
kind: Service
metadata:
  name: any-sync-consensusnode
  namespace: {{ .Values.namespace }}
  annotations:
    lbipam.cilium.io/ips: {{ .Values.consensusnode.lbIP | quote }}
spec:
  type: LoadBalancer
  selector:
    app: any-sync-consensusnode
  ports:
    - name: tcp
      port: {{ .Values.consensusnode.ports.tcp }}
      targetPort: {{ .Values.consensusnode.ports.tcp }}
      protocol: TCP
    - name: quic
      port: {{ .Values.consensusnode.ports.quic }}
      targetPort: {{ .Values.consensusnode.ports.quic }}
      protocol: UDP
