apiVersion: v1
kind: Service
metadata:
  name: any-sync-coordinator
  namespace: {{ .Values.namespace }}
  annotations:
    lbipam.cilium.io/ips: {{ .Values.coordinator.lbIP | quote }}
    lbipam.cilium.io/sharing-key: "anytype"
    lbipam.cilium.io/sharing-cross-namespace: "*"
spec:
  type: LoadBalancer
  selector:
    app: any-sync-coordinator
  ports:
    - name: tcp
      port: {{ .Values.coordinator.ports.tcp }}
      targetPort: {{ .Values.coordinator.ports.tcp }}
      protocol: TCP
    - name: quic
      port: {{ .Values.coordinator.ports.quic }}
      targetPort: {{ .Values.coordinator.ports.quic }}
      protocol: UDP
