apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filenode-networkstore
  namespace: {{ .Values.namespace }}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: {{ .Values.filenode.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.filenode.storage.size }}
