---
apiVersion: v1
kind: Service
metadata:
  name: mongo-1
  namespace: {{.Values.namespace}}
spec:
  clusterIP: None
  selector:
    app: mongo-1
  ports:
    - port: {{.Values.mongodb.port}}
      targetPort: {{.Values.mongodb.port}}
