apiVersion: v1
kind: Service
metadata:
  name: any-sync-node
  namespace: {{ .Values.namespace }}
  annotations:
    lbipam.cilium.io/ips: {{ .Values.syncnode.lbIP | quote }}
spec:
  type: LoadBalancer
  selector:
    app: any-sync-node
  ports:
    - name: tcp
      port: {{ .Values.syncnode.ports.tcp }}
      targetPort: {{ .Values.syncnode.ports.tcp }}
      protocol: TCP
    - name: quic
      port: {{ .Values.syncnode.ports.quic }}
      targetPort: {{ .Values.syncnode.ports.quic }}
      protocol: UDP
