postgres:
  name: home-assistant
  instances: 2
  storage:
    size: 5Gi
  monitoring:
    enablePodMonitor: true
  backup:
    retentionPolicy: "10d"
    barmanObjectStore:
      destinationPath: "s3://k8s-at-home-backup/cnpg/home-assistant"
      endpointURL: <secret:s3_endpoint>
      s3Credentials:
        accessKeyId:
          name: home-assistant-secrets
          key: S3_ACCESS_KEY_ID
        secretAccessKey:
          name: home-assistant-secrets
          key: S3_ACCESS_SECRET_KEY
  scheduledBackups:
    - name: home-assistant-cnpg-backup
      spec:
        immediate: true
        schedule: "52 0 0 * * *"
        backupOwnerReference: self
app-template:
  defaultPodOptions:
    securityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
  controllers:
    main:
      type: statefulset
      strategy: RollingUpdate
      containers:
        main:
          image:
            repository: ghcr.io/home-assistant/home-assistant
            tag: 2026.3.2@sha256:572a5d030f652e9ef6c6d4f6631169af83eb3b739c9b4b3965669f5e9d9f3858
          envFrom:
            - secretRef:
                name: home-assistant-secret
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
            limits:
              memory: 750Mi
    addons:
      containers:
        codeserver:
          image:
            repository: ghcr.io/coder/code-server
            tag: 4.112.0@sha256:ddd9b0b854fec5a3c65ec0095b5c59fb8505ad44d8a18d00d6fcf6a3179692dd
          workingDir: "/config"
          args:
            - --auth
            - "none"
            - --user-data-dir
            - "/config/.vscode"
            - --extensions-dir
            - "/config/.vscode"
  service:
    main:
      controller: main
      ports:
        http:
          port: 8123
    codeserver:
      controller: addons
      ports:
        http:
          port: 8080
  route:
    main:
      annotations:
        external-dns.alpha.kubernetes.io/controller: dns-controller
      parentRefs:
        - name: envoy-internal
          namespace: envoy-gateway
          sectionName: https
      hostnames:
        - dom.<secret:private-domain>
      rules:
        - backendRefs:
            - identifier: main
    addons:
      annotations:
        external-dns.alpha.kubernetes.io/controller: dns-controller
      parentRefs:
        - name: envoy-internal
          namespace: envoy-gateway
          sectionName: https
      hostnames:
        - dom-code.<secret:private-domain>
      rules:
        - backendRefs:
            - identifier: codeserver
  persistence:
    config:
      existingClaim: home-assistant-config
