apiVersion: v1
kind: ConfigMap
metadata:
  name: vernemq-config-tpl
data:
  templated: |
    DOCKER_VERNEMQ_USER_{{`{{ .admin_username }}`}}: {{`{{ .admin_password }}`}}
    DOCKER_VERNEMQ_USER_{{`{{ .home_assistant_username }}`}}: {{`{{ .home_assistant_password }}`}}
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vernemq
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: vernemq-users
    creationPolicy: Owner
    template:
      engineVersion: v2
      templateFrom:
        - target: Data
          configMap:
            name: vernemq-config-tpl
            items:
              - key: templated
                templateAs: KeysAndValues
  data:
    - secretKey: admin_username
      remoteRef:
        key: "51a18ec8-bede-48ab-b519-b40a00d706e9" #gitleaks:allow #VERNEMQ_ADMIN_USERNAME
    - secretKey: admin_password
      remoteRef:
        key: "b41c1bad-ee30-4007-99cc-b40a00d72284" #gitleaks:allow #VERNEMQ_ADMIN_PASSWORD
    - secretKey: home_assistant_username
      remoteRef:
        key: "05543802-765d-45dc-b97a-b40a00d743b1" #gitleaks:allow #VERNEMQ_HOME_ASSISTANT_USERNAME
    - secretKey: home_assistant_password
      remoteRef:
        key: "f872ad0e-cc13-42ec-b3b8-b40a00d76098" #gitleaks:allow #VERNEMQ_HOME_ASSISTANT_PASSWORD
