apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: adguard-dns
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: adguard-dns-secret
    template:
      data:
        ADGUARD_URL: '{{ `{{ .ADGUARD_URL }}` }}'
        ADGUARD_USER: '{{ `{{ .ADGUARD_USER }}` }}'
        ADGUARD_PASSWORD: '{{ `{{ .ADGUARD_PASSWORD }}` }}'
        ADGUARD_DOMAIN_FILTER: '{{ `{{ .ADGUARD_DOMAIN_FILTER }}` }}'
  data:
  - secretKey: ADGUARD_URL
    remoteRef:
      key: "3f470a72-941f-4792-81d2-b40800e9d5b6" #gitleaks:allow
  - secretKey: ADGUARD_USER
    remoteRef:
      key: "7e657efe-c9fa-420d-8959-b40800e9dea5" #gitleaks:allow
  - secretKey: ADGUARD_PASSWORD
    remoteRef:
      key: "6ccac8f0-d23e-48da-ae23-b40800e9e7f0" #gitleaks:allow
  - secretKey: ADGUARD_DOMAIN_FILTER
    remoteRef:
      key: "5bac8149-5d3a-42a7-ad93-b40800e9f261" #gitleaks:allow
