apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: adguard-dns
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: adguard-dns-secret
    template:
      data:
        ADGUARD_URL: '{{ `{{ .ADGUARD_URL }}` }}'
        ADGUARD_USER: '{{ `{{ .ADGUARD_USER }}` }}'
        ADGUARD_PASSWORD: '{{ `{{ .ADGUARD_PASSWORD }}` }}'
        ADGUARD_DOMAIN_FILTER: '{{ `{{ .ADGUARD_DOMAIN_FILTER }}` }}'
  data:
  - secretKey: ADGUARD_URL
    remoteRef:
      key: "aa" #gitleaks:allow
  - secretKey: ADGUARD_USER
    remoteRef:
      key: "aa" #gitleaks:allow
  - secretKey: ADGUARD_PASSWORD
    remoteRef:
      key: "aa" #gitleaks:allow
  - secretKey: ADGUARD_DOMAIN_FILTER
    remoteRef:
      key: "aa" #gitleaks:allow
