- enabled: "true"
  namespace: vintagestory
  syncPolicy:
    enabled: true
    selfHeal: false
    prune: false
  plugin:
    env:
      - name: SECRET_PROVIDER
        value: cluster-secrets
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      name: vintagestory
      jsonPointers:
        - /spec/replicas
