Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.box_check_update = true

  config.vm.define "tm1" do |master|
    master.vm.hostname = "tm1"
    master.vm.network "private_network", ip: "10.0.0.11"
    master.vm.provider "virtualbox" do |vb|
      vb.memory = 4048
      vb.cpus = 4
    end
    master.vm.provision "shell", path: "scripts/common.sh", privileged: false
  end

  config.vm.define "tm2" do |master|
    master.vm.hostname = "tm2"
    master.vm.network "private_network", ip: "10.0.0.12"
    master.vm.provider "virtualbox" do |vb|
      vb.memory = 4048
      vb.cpus = 4
    end
    master.vm.provision "shell", path: "scripts/common.sh", privileged: false
  end
end
