apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: headlamp-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  refreshInterval: 1h
  target:
    name: headlamp-oidc
    creationPolicy: Owner
    template:
      data:
        OIDC_SCOPES: "openid profile email"
        OIDC_CLIENT_ID: '{{ `{{ .OIDC_CLIENT_ID }}` }}'
        OIDC_CLIENT_SECRET: '{{ `{{ .OIDC_CLIENT_SECRET }}` }}'
        OIDC_ISSUER_URL: '{{ `{{ .OIDC_ISSUER_URL }}` }}'
  data:
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        key: "a3b45da4-8e79-4900-9660-b44901588ca4" #gitleaks:allow #HEADLAMP_OIDC_CLIENT_ID
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: "4494aec7-b90d-48a0-bf58-b4490158d405" #gitleaks:allow #HEADLAMP_OIDC_CLIENT_SECRET
    - secretKey: OIDC_ISSUER_URL
      remoteRef:
        key: "529f878b-e72d-4c60-a681-b4490158f134" #gitleaks:allow #HEADLAMP_OIDC_ISSUER_URL
