- enabled: "true"
  namespace: external-secrets
  syncPolicy:
    enabled: true
    selfHeal: true
    prune: false
  ignoreDifferences:
    - kind: Secret
      name: bitwarden-access-token
      jsonPointers:
        - /data
