hermes:
  image:
    repository: nousresearch/hermes-agent
    tag: "main@sha256:3555b9eb722bca03b81815a1b309602a345604e5cfcf2c5f42e2b496fd115722"
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      memory: 1Gi

signalCli:
  image:
    repository: bbernhard/signal-cli-rest-api
    tag: "0.99@sha256:96578363477d97cb1d8da303791b2ad686b374a255fce4d78c7c6f00ef56cba8"
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 1Gi
