apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zigbee2mqtt-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  refreshInterval: 1h
  target:
    name: zigbee2mqtt-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ZIGBEE2MQTT_CONFIG_MQTT_SERVER: "mqtt://home-assistant-mqtt-rmq.ha-rabbitmq.svc.cluster.local:1883"
        ZIGBEE2MQTT_CONFIG_MQTT_USER: "{{ `{{ .USERNAME }}` }}"
        ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: "{{ `{{ .PASSWORD }}` }}"
  data:
    - secretKey: USERNAME
      remoteRef:
        key: "7b52fc44-cd89-4f72-869b-b4d7009c58c4" #gitleaks:allow #RABBITMQ_ZIGBEE2MQTT_USERNAME
    - secretKey: PASSWORD
      remoteRef:
        key: "e67a02c7-9a79-4e60-b522-b4d7009ca875" #gitleaks:allow #RABBITMQ_ZIGBEE2MQTT_PASSWORD
