---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      # 1. Define an emptyDir volume which will hold the custom binaries
      volumes:
        - configMap:
            name: sops-replacer-plugin
          name: sops-replacer-plugin
        - name: cluster-secrets
          secret:
            secretName: cluster-secrets
        - name: tmp-secret-replacer-plugin
          emptyDir: {}
      # 3. Volume mount the custom binary to the bin directory (overriding the existing version)
      containers:
        - name: secret-replacer-plugin-kustomize
          command: [/var/run/argocd/argocd-cmp-server]
          image: ghcr.io/mmalyska/argocd-secret-replacer:rolling@sha256:db44e6479bf6776441f5744a94674dc56861d1af5f3fa0b6a479ec220ba50a3a
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 16Mi
          volumeMounts:
            - mountPath: /var/run/argocd
              name: var-files
            - mountPath: /home/argocd/cmp-server/plugins
              name: plugins
            - mountPath: /tmp
              name: tmp-secret-replacer-plugin
            - mountPath: /home/argocd/cmp-server/config/plugin.yaml
              name: sops-replacer-plugin
              subPath: secret-replacer-plugin-kustomize.yaml
            - mountPath: /cluster-secrets
              name: cluster-secrets
              readOnly: true
        - name: secret-replacer-plugin-helm
          command: [/var/run/argocd/argocd-cmp-server]
          image: ghcr.io/mmalyska/argocd-secret-replacer:rolling@sha256:db44e6479bf6776441f5744a94674dc56861d1af5f3fa0b6a479ec220ba50a3a
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 16Mi
          env:
            - name: HELM_CACHE_HOME
              value: /helm-working-dir
            - name: HELM_CONFIG_HOME
              value: /helm-working-dir
            - name: HELM_DATA_HOME
              value: /helm-working-dir
          volumeMounts:
            - mountPath: /var/run/argocd
              name: var-files
            - mountPath: /home/argocd/cmp-server/plugins
              name: plugins
            - mountPath: /tmp
              name: tmp-secret-replacer-plugin
            - mountPath: /home/argocd/cmp-server/config/plugin.yaml
              name: sops-replacer-plugin
              subPath: secret-replacer-plugin-helm.yaml
            - mountPath: /cluster-secrets
              name: cluster-secrets
              readOnly: true
            - mountPath: /helm-working-dir
              name: helm-working-dir
