apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-admin-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  refreshInterval: 1h
  target:
    name: nextcloud-admin-secret
    creationPolicy: Owner
  data:
    - secretKey: nextcloud-username
      remoteRef:
        key: "<BITWARDEN_UUID_nextcloud-admin-username>" #gitleaks:allow #NEXTCLOUD_ADMIN_USERNAME
    - secretKey: nextcloud-password
      remoteRef:
        key: "<BITWARDEN_UUID_nextcloud-admin-password>" #gitleaks:allow #NEXTCLOUD_ADMIN_PASSWORD
