apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-oidc-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  refreshInterval: 1h
  target:
    name: nextcloud-oidc-secret
    creationPolicy: Owner
  data:
    - secretKey: client_secret
      remoteRef:
        key: "<BITWARDEN_UUID_nextcloud-oidc-client-secret>" #gitleaks:allow #NEXTCLOUD_OIDC_CLIENT_SECRET
