apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-redis-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  refreshInterval: 1h
  target:
    name: nextcloud-redis-auth
    creationPolicy: Owner
  data:
    - secretKey: redis-password
      remoteRef:
        key: "<BITWARDEN_UUID_nextcloud-redis-password>" #gitleaks:allow #NEXTCLOUD_REDIS_PASSWORD
