apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-redis-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  refreshInterval: 1h
  target:
    name: nextcloud-redis-auth
    creationPolicy: Owner
  data:
    - secretKey: redis-password
      remoteRef:
        key: "9e30a3df-5081-4a76-af95-b47c00736541" #gitleaks:allow #NEXTCLOUD_REDIS_PASSWORD
