apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-s3-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  refreshInterval: 1h
  target:
    name: nextcloud-s3-secret
    creationPolicy: Owner
  data:
    - secretKey: S3_ACCESS_KEY_ID
      remoteRef:
        key: "<BITWARDEN_UUID_nextcloud-s3-access-key-id>" #gitleaks:allow #NEXTCLOUD_S3_ACCESS_KEY
    - secretKey: S3_ACCESS_SECRET_KEY
      remoteRef:
        key: "<BITWARDEN_UUID_nextcloud-s3-secret-access-key>" #gitleaks:allow #NEXTCLOUD_S3_SECRET_KEY
