eg:
  config:
    envoyGateway:
      extensionApis:
        enableEnvoyPatchPolicy: true
      provider:
        type: Kubernetes
        kubernetes:
          deploy:
            type: GatewayNamespace
