- enabled: "true"
  namespace: argocd
  syncPolicy:
    enabled: false
    selfHeal: true
    prune: false
  plugin:
    env:
      - name: SECRET_PROVIDER
        value: cluster-secrets
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: argocd-secret
      jsonPointers:
        - /data/oidc.keycloak.clientSecret
