---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: argocd

namespace: argocd

# additional resources like ingress rules, cluster and repository secrets.
resources:
  - resources/httproute.yaml
  - https://github.com/argoproj/argo-cd/manifests/cluster-install?ref=v3.3.7
  - resources/sops-replacer-plugin.yaml
  - resources/metrics.yaml
  - resources/cluster-secrets-externalsecret.yaml
  - resources/repository-externalsecret.yaml
  - resources/argocd-oidc-externalsecret.yaml

# changes to config maps
patches:
  - path: patches/argocd-cm.yaml
  - path: patches/argocd-rbac-cm.yaml
  - path: patches/argocd-cmd-params-cm.yaml
  - path: patches/argo-cd-repo-server-ksops-patch.yaml
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/revisionHistoryLimit
        value: 3
