homepage:
  config:
    bookmarks:
      - Developer:
          - Github:
              - abbr: GH
                href: https://github.com/
    widgets:
      # show the kubernetes widget, with the cluster summary and individual nodes
      - kubernetes:
          cluster:
            show: true
            cpu: true
            memory: true
            showLabel: true
            label: "cluster"
          nodes:
            show: true
            cpu: true
            memory: true
            showLabel: true
      - search:
          provider: duckduckgo
          target: _blank
    kubernetes:
      mode: cluster
    settings:

  # The service account is necessary to allow discovery of other services
  serviceAccount:
    create: true
    name: homepage

  # This enables the service account to access the necessary resources
  enableRbac: true

  ingress:
    main:
      enabled: false
