---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: vs-game
  namespace: vintagestory
  annotations:
    external-dns.alpha.kubernetes.io/controller: internal
spec:
  endpoints:
    - dnsName: vs.game.<secret:private-domain>
      recordType: A
      targets:
        - "192.168.48.28"
