apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hermes-agent
  namespace: hermes-agent
  annotations:
    external-dns.alpha.kubernetes.io/controller: dns-controller
spec:
  parentRefs:
    - name: envoy-internal
      namespace: envoy-gateway
      sectionName: https
  hostnames:
    - hermes.<secret:private-domain>
  rules:
    - backendRefs:
        - name: hermes-agent
          port: 9119
