apiVersion: apps/v1
kind: Deployment
metadata:
  name: signal-cli
  namespace: hermes-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: signal-cli
  template:
    metadata:
      labels:
        app: signal-cli
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: signal-cli
          image: "{{ .Values.signalCli.image.repository }}:{{ .Values.signalCli.image.tag }}"
          command: ["/usr/bin/signal-cli"]
          args:
            - "--config"
            - "/home/.local/share/signal-cli"
            - "daemon"
            - "--http"
            - "0.0.0.0:8080"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources: {{toYaml .Values.signalCli.resources | nindent 12}}
          volumeMounts:
            - name: data
              mountPath: /home/.local/share/signal-cli
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: hermes-signal-data
