apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cert-manager-api-token
  namespace: cert-manager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  refreshInterval: 1h
  target:
    name: cloudflare-api-token-secret
    creationPolicy: Owner
  data:
    - secretKey: api-token
      remoteRef:
        key: "b3e17897-b005-49aa-958a-b409016d4c50" #gitleaks:allow #CERT_MANAGER_API_TOKEN
