apiVersion: v1
kind: Service
metadata:
  name: honcho
  namespace: honcho
spec:
  type: ClusterIP
  selector:
    app: honcho-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
