apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-dragonfly-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  refreshInterval: 1h
  target:
    name: harbor-dragonfly-auth
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        REDIS_PASSWORD: "{{ `{{ .password }}` }}"
        password: "{{ `{{ .password }}` }}"
  data:
    - secretKey: password
      remoteRef:
        key: "e6560beb-d2d1-4b2e-b5e8-b48100bb161f" #gitleaks:allow #HARBOR_DRAGONFLY_PASSWORD
