apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-oidc-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  refreshInterval: 1h
  target:
    name: harbor-oidc-secret
    creationPolicy: Owner
    template:
      data:
        CONFIG_OVERWRITE_JSON: '{"auth_mode":"oidc_auth","oidc_name":"Keycloak","oidc_endpoint":"https://l.{{ `{{ .private_domain }}` }}/realms/home","oidc_client_id":"harbor","oidc_client_secret":"{{ `{{ .oidc_client_secret }}` }}","oidc_scope":"openid,profile,email,groups","oidc_groups_claim":"groups","oidc_user_claim":"preferred_username","oidc_auto_onboard":true,"oidc_verify_cert":true}'
  data:
    - secretKey: private_domain
      remoteRef:
        key: "ce4d5e10-c9b7-4ed8-a519-b40901579a80" #gitleaks:allow #CLUSTER_SECRET_PRIVATE_DOMAIN
    - secretKey: oidc_client_secret
      remoteRef:
        key: "3ef94175-15dd-45a0-81f6-b46201502dac" #gitleaks:allow #HARBOR_KEYCLOAK_OIDC_CLIENT_SECRET
