- enabled: "true"
  appSubfolder: embeddings
  namespace: llm
  syncPolicy:
    enabled: true
    selfHeal: true
    prune: false
  managedNamespaceMetadata:
    labels:
      pod-security.kubernetes.io/enforce: baseline
      pod-security.kubernetes.io/warn: baseline
- enabled: "false"
  appSubfolder: server
  namespace: llm
  syncPolicy:
    enabled: true
    selfHeal: true
    prune: false
  managedNamespaceMetadata:
    labels:
      pod-security.kubernetes.io/enforce: baseline
      pod-security.kubernetes.io/warn: baseline
- enabled: "false"
  appSubfolder: stt
  namespace: llm
  syncPolicy:
    enabled: true
    selfHeal: true
    prune: false
  managedNamespaceMetadata:
    labels:
      pod-security.kubernetes.io/enforce: baseline
      pod-security.kubernetes.io/warn: baseline
