apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-dragonfly-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  refreshInterval: 1h
  target:
    name: gitea-dragonfly-auth
    creationPolicy: Owner
  data:
    - secretKey: redis-password
      remoteRef:
        key: "8079ea1a-bdc1-41f2-b34a-b48100bd40c0" #gitleaks:allow #GITEA_DRAGONFLY_PASSWORD
