persistance:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
minecraft-bedrock:
  image:
    repository: itzg/minecraft-bedrock-server
    tag: 2026.5.3@sha256:d0aa4e6726adba217e6a38fcc56320ac948272f06fc21b8a0788dc8f56edaad7
    pullPolicy: IfNotPresent
  persistence:
    dataDir:
      enabled: true
      existingClaim: minecraft-bedrock-datadir
      Size: 10Gi
  resources:
    requests:
      memory: 250Mi
      cpu: 200m
    limits:
      memory: 2Gi
  minecraftServer:
    eula: "TRUE"
    version: 1.21.111.1
    difficulty: normal
    gameMode: survival
    levelName: jaskinia
    serverName: "Jaskinia"
    cheats: false
    serviceType: LoadBalancer
    loadBalancerIP: 192.168.48.23
    ops: <secret:ops>
    defaultPermission: visitor
    whitelistUsers: <secret:whitelistUsers>
