apiVersion: batch/v1
kind: CronJob
metadata:
  name: talos-backup-cleaner
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: talos-backup-cleaner
              image: ghcr.io/mmalyska/s3-bucket-cleaner:2.35.11@sha256:c743b96e644a7c522926e7713c97c9f5622afc49e4c604fe7272be2a1ea97c60
              imagePullPolicy: IfNotPresent
              env:
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: talos-backup-doppler
                      key: AWS_ACCESS_KEY_ID
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: talos-backup-doppler
                      key: AWS_SECRET_ACCESS_KEY
                - name: AWS_REGION
                  value: us-west-2
                - name: AWS_ENDPOINT_URL_S3
                  valueFrom:
                    secretKeyRef:
                      name: talos-backup-doppler
                      key: CUSTOM_S3_ENDPOINT
                - name: BUCKET
                  value: "talos-backup"
                - name: S3_PREFIX
                  value: "etcd"
                - name: OLDER_THAN
                  value: "7 days ago"
              resources:
                requests:
                  memory: 25Mi
                  cpu: 100m
                limits:
                  memory: 100Mi
                  cpu: 250m

          restartPolicy: OnFailure

---
