apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: talos-backup
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: talos-backup-doppler
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        CUSTOM_S3_ENDPOINT: '{{`{{ .CUSTOM_S3_ENDPOINT }}`}}'
        AWS_ACCESS_KEY_ID: '{{`{{ .AWS_ACCESS_KEY_ID }}`}}'
        AWS_SECRET_ACCESS_KEY: '{{`{{ .AWS_SECRET_ACCESS_KEY }}`}}'
  data:
    - secretKey: CUSTOM_S3_ENDPOINT
      remoteRef:
        key: "3f8708ab-893b-4aaf-ab5d-b40a00d6ac4b" #gitleaks:allow #TALOS_BACKUP_CUSTOM_S3_ENDPOINT
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: "002c6744-1ba7-4da2-a0a5-b40a00d6ca0d" #gitleaks:allow #TALOS_BACKUP_AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: "95cee970-cac8-434d-a045-b40a00d6e414" #gitleaks:allow #TALOS_BACKUP_AWS_SECRET_ACCESS_KEY
