open-webui:
  persistence:
    size: 5Gi
  ollama:
    enabled: false
  ingress:
    enabled: false
  route:
    enabled: true
    annotations:
      external-dns.alpha.kubernetes.io/controller: dns-controller
    parentRefs:
      - name: envoy-internal
        namespace: envoy-gateway
        sectionName: https
    hostnames:
      - chat.<secret:private-domain>
  image:
    repository: ghcr.io/open-webui/open-webui
    tag: "v0.11.3@sha256:d428020d5f091491cf1ef6a186a7fd080f388bfbf2c2c221b78a3b1bead0d591"
    pullPolicy: "IfNotPresent"
  resources:
    requests:
      memory: 1100Mi
      cpu: 300m
    limits:
      memory: 2Gi
      cpu: "1"
  websocket:
    enabled: false
