open-webui:
  persistence:
    size: 5Gi
  ollama:
    enabled: false
  ingress:
    enabled: false
  route:
    enabled: true
    annotations:
      external-dns.alpha.kubernetes.io/controller: dns-controller
    parentRefs:
      - name: envoy-internal
        namespace: envoy-gateway
        sectionName: https
    hostnames:
      - chat.<secret:private-domain>
  image:
    repository: ghcr.io/open-webui/open-webui
    tag: "v0.10.2@sha256:9fcea9c6e32ab60b0498f3986c6cdf651ddbe61db48d2213a3d28048ddd673d4"
    pullPolicy: "IfNotPresent"
  resources:
    requests:
      memory: 1100Mi
      cpu: 300m
    limits:
      memory: 2Gi
      cpu: "1"
  websocket:
    enabled: false
