nameOverride:
secretSyncWave: "-2"
syncWave: "-1"
pvc:
  existingClaim: "" # If set, skip PVC creation and use this PVC name for source/destination
  accessMode: ReadWriteOnce
  capacity: 5Gi
  storageClass: ceph-block
  volumeSnapshotClass: csi-ceph-blockpool
volsync:
  moverSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  backup:
    schedule: "30 */12 * * *"
    pruneIntervalDays: 14
    retain:
      hourly: 24
      daily: 7
      weekly: 4
      monthly: 2
  restore:
    bootstrap: true
