---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wow-client-data
  namespace: wow
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
