---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wow-mysql
  namespace: wow
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  refreshInterval: 1h
  target:
    name: wow-mysql-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        MYSQL_ROOT_PASSWORD: '{{`{{ .MYSQL_ROOT_PASSWORD }}`}}'
        MYSQL_PASSWORD: '{{`{{ .MYSQL_PASSWORD }}`}}'
        AC_LOGIN_DATABASE_INFO: 'mysql;3306;acore;{{`{{ .MYSQL_PASSWORD }}`}};acore_auth'
        AC_WORLD_DATABASE_INFO: 'mysql;3306;acore;{{`{{ .MYSQL_PASSWORD }}`}};acore_world'
        AC_CHARACTER_DATABASE_INFO: 'mysql;3306;acore;{{`{{ .MYSQL_PASSWORD }}`}};acore_characters'
        AC_LOGIN_DATABASE_INFO_ROOT: 'mysql;3306;root;{{`{{ .MYSQL_ROOT_PASSWORD }}`}};acore_auth'
        AC_WORLD_DATABASE_INFO_ROOT: 'mysql;3306;root;{{`{{ .MYSQL_ROOT_PASSWORD }}`}};acore_world'
        AC_CHARACTER_DATABASE_INFO_ROOT: 'mysql;3306;root;{{`{{ .MYSQL_ROOT_PASSWORD }}`}};acore_characters'
  data:
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: "7471542b-ab56-424c-b617-b446012f1c3f" #gitleaks:allow #WOW_MYSQL_ROOT_PASSWORD
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: "208505b7-149e-4b70-9e12-b446012f5258" #gitleaks:allow #WOW_MYSQL_ACORE_PASSWORD
