---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mosquitto-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  refreshInterval: 1h
  target:
    name: mosquitto-secret
    creationPolicy: Owner
  data:
    - secretKey: HOME_ASSISTANT_USERNAME
      remoteRef:
        key: "05543802-765d-45dc-b97a-b40a00d743b1" #gitleaks:allow #RABBITMQ_HOME_ASSISTANT_USERNAME (shared with the broker it replaces)
    - secretKey: HOME_ASSISTANT_PASSWORD
      remoteRef:
        key: "f872ad0e-cc13-42ec-b3b8-b40a00d76098" #gitleaks:allow #RABBITMQ_HOME_ASSISTANT_PASSWORD
    - secretKey: ZIGBEE2MQTT_USERNAME
      remoteRef:
        key: "7b52fc44-cd89-4f72-869b-b4d7009c58c4" #gitleaks:allow #RABBITMQ_ZIGBEE2MQTT_USERNAME
    - secretKey: ZIGBEE2MQTT_PASSWORD
      remoteRef:
        key: "e67a02c7-9a79-4e60-b522-b4d7009ca875" #gitleaks:allow #RABBITMQ_ZIGBEE2MQTT_PASSWORD
