ollama:
  ollama:
    models:
      pull:
        - deepcoder:14b
        - llama3.2:3b
  extraEnv:
    - name: OLLAMA_NUM_PARALLEL
      value: "2"
  service:
    annotations:
      lbipam.cilium.io/sharing-key: "voice-pipeline"
      lbipam.cilium.io/sharing-cross-namespace: "*"
      lbipam.cilium.io/ips: "192.168.48.27"
    type: LoadBalancer
  ingress:
    enabled: false
  persistentVolume:
    enabled: true
    size: "100Gi"
  resources:
    limits:
      gpu.intel.com/i915: 1
      memory: 16Gi
    requests:
      gpu.intel.com/i915: 1
      cpu: 500m
      memory: 8Gi
