apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dyndns-secret
  namespace: dyndns
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  refreshInterval: 1h
  target:
    name: dyndns-secret
    creationPolicy: Owner
    template:
      data:
        config.yaml: "{{ `{{ .CONFIG_YAML }}` }}"
  data:
    - secretKey: CONFIG_YAML
      remoteRef:
        key: "047b9800-a078-4fa6-b68b-b40a008faaa3" #gitleaks:allow #DYNDNS_CONFIG_YAML
