---
apiVersion: v2
name: litellm
type: application
version: 1.0.0
dependencies:
  - name: litellm-helm
    version: 1.89.4
    repository: oci://ghcr.io/berriai
  - name: pgsql-cnpg
    version: 1.3.2
    repository: file://../../../../charts/pgsql-cnpg/
