#!/usr/bin/env bash
# config-map.sh [--check] [out-file]
# Generate the Talos configuration map for the docs (default docs/src/talos/config-map.md) from the
# patch headers. It needs no secrets and no cluster. With --check, write nothing and exit 1 when the
# file differs from what would be generated (CI uses this to catch a stale map).
set -euo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
SCRIPTS="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

check=0
if [ "${1:-}" = "--check" ]; then check=1; shift; fi
out="${1:-$TALOS_DIR/../../docs/src/talos/config-map.md}"

tmp="$(mktemp)"; trap 'rm -f "$tmp"' EXIT
{
  cat <<'DOC'
<!-- markdownlint-disable MD013 -->

# Talos configuration map

> Generated by `task talos:config-map` from the headers of the files under `provision/talos/patches/`. Do not edit.
> Files are listed in merge order (later files win); see `provision/talos/README.md` for how they are applied.
> Apply: `live` takes effect immediately, `install-only` only matters at the next install or upgrade,
> `reboot` takes effect only after a node reboot.

DOC
  "$SCRIPTS/explain.sh" --markdown
} > "$tmp"

if [ "$check" -eq 1 ]; then
  [ -f "$out" ] || { echo "config-map: $out does not exist; run task talos:config-map" >&2; exit 1; }
  diff -u "$out" "$tmp" >&2 || { echo "config-map: $out is stale; run task talos:config-map" >&2; exit 1; }
  echo "config-map: up to date"
else
  mkdir -p "$(dirname "$out")"
  cp "$tmp" "$out"
  echo "config-map: wrote $out"
fi
