apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: cloudflared-secret
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: CLOUDFLARE_TUNNEL_TOKEN
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: cloudflare-tunnel-secret
    template:
      data:
        CF_TUNNEL_INGRESS: "{{ .CLOUDFLARE_TUNNEL_INGRESS }}"
  data:
  - secretKey: CLOUDFLARE_TUNNEL_INGRESS
    remoteRef:
      key: "8f4d213f-69ed-4728-add5-b4070118cde5" #gitleaks:allow #CLOUDFLARE_TUNNEL_INGRESS
