apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: cloudflared-secret
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: CLOUDFLARE_TUNNEL_TOKEN
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: cloudflare-tunnel-secret
  data:
    - secretKey: CF_TUNNEL_INGRESS
      remoteRef:
        key: "8f4d213f-69ed-4728-add5-b4070118cde5" #gitleaks:allow #CLOUDFLARE_TUNNEL_INGRESS
    - secretKey: CF_TUNNEL_TOKEN
      remoteRef:
        key: "450dd9e3-ed89-4508-8c98-b4070159e6cc" #gitleaks:allow #CLOUDFLARE_TUNNEL_TOKEN
