apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: cloudflare-tunnel-secret
    template:
      data:
        CF_TUNNEL_INGRESS: |
          {{ .CLOUDFLARE_TUNNEL_INGRESS }}
        CF_TUNNEL_SECRET: |-
          "{{ toJson (dict "a" .CLOUDFLARE_ACCOUNT_TAG "t" .CLOUDFLARE_TUNNEL_ID "s" .CLOUDFLARE_TUNNEL_SECRET) | b64enc }}"
  data:
    - secretKey: CLOUDFLARE_TUNNEL_INGRESS
      remoteRef:
        key: "8f4d213f-69ed-4728-add5-b4070118cde5" #gitleaks:allow
    - secretKey: CLOUDFLARE_ACCOUNT_TAG
      remoteRef:
        key: "46669c66-792d-4ce7-aa22-b408008e5bf8" #gitleaks:allow
    - secretKey: CLOUDFLARE_TUNNEL_ID
      remoteRef:
        key: "50908d50-6976-49ad-afd1-b408008ea4bf" #gitleaks:allow
    - secretKey: CLOUDFLARE_TUNNEL_SECRET
      remoteRef:
        key: "95af22e2-6375-46d2-9f29-b407016beadb" #gitleaks:allow
