prometheus-smartctl-exporter:
  image:
    repository: ghcr.io/home-operations/smartctl-exporter
    tag: "0.14.0@sha256:773d462bb82db3195b050fbe71b08caf62fe0ad6b4abfb63a4b8306f5bb7516a"

  config:
    devices:
      - /dev/sda
      - /dev/nvme0n1

  serviceMonitor:
    enabled: true
    interval: 60s
    scrapeTimeout: 30s

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values: [mc1, mc2, mc3]

  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 50m
      memory: 64Mi

  extraInstances:
    - config:
        devices:
          - /dev/nvme0n1
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values: [nv1]
      tolerations:
        - key: nv
          operator: Equal
          value: NoSchedule
          effect: NoSchedule
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          cpu: 50m
          memory: 64Mi
