prometheus-smartctl-exporter:
  config:
    devices:
      - /dev/sda
      - /dev/nvme0n1

  serviceMonitor:
    enabled: true
    interval: 60s
    scrapeTimeout: 30s

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values: [mc1, mc2, mc3]

  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 50m
      memory: 64Mi

  extraInstances:
    - config:
        devices:
          - /dev/nvme0n1
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values: [nv1]
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          cpu: 50m
          memory: 64Mi
