---
apiVersion: v2
name: harbor
type: application
version: 1.0.0
dependencies:
  - name: harbor
    version: 1.19.1
    repository: https://helm.goharbor.io
  - name: pgsql-cnpg
    version: 1.3.2
    repository: file://../../../../charts/pgsql-cnpg/
