---
apiVersion: v2
name: harbor
type: application
version: 1.0.0
dependencies:
  - name: harbor
    version: 1.19.2
    repository: https://helm.goharbor.io
  - name: pgsql-cnpg
    version: 1.4.0
    repository: file://../../../../charts/pgsql-cnpg/
  - name: dragonfly
    version: 1.0.1
    repository: file://../../../../charts/dragonfly/
