apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-credentials
  namespace: oauth2-proxy
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  refreshInterval: 1h
  target:
    name: oauth-secret
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: "9a4b895e-6856-4d88-8ee7-b409016f2d84" #gitleaks:allow #OAUTH2_PROXY_CLIENT_ID
    - secretKey: client-secret
      remoteRef:
        key: "2f3425bd-46fc-4461-825f-b409016f4530" #gitleaks:allow #OAUTH2_PROXY_CLIENT_SECRET
    - secretKey: cookie-secret
      remoteRef:
        key: "cb49d906-c8e5-46d6-9db8-b409016f5ccf" #gitleaks:allow #OAUTH2_PROXY_COOKIE_SECRET
    - secretKey: redis-password
      remoteRef:
        key: "16888cc9-dd0f-472b-a822-b409016f77e0" #gitleaks:allow #OAUTH2_PROXY_REDIS_PASSWORD
