# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  refreshInterval: 1h
  target:
    name: home-assistant-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SECRET_EXTERNAL_URL: "https://dom.<secret:private-domain>"
        SECRET_MQTT_USERNAME: "{{ `{{ .HOME_ASSISTANT_USERNAME }}` }}"
        SECRET_MQTT_PASSWORD: "{{ `{{ .HOME_ASSISTANT_PASSWORD }}` }}"
        SECRET_MQTT_HOST: "mqtt://vernemq.ha-vernemq.svc.cluster.local"
        S3_ACCESS_KEY_ID: "{{ `{{ .S3_ACCESS_KEY }}` }}"
        S3_ACCESS_SECRET_KEY: "{{ `{{ .S3_SECRET_KEY }}` }}"
  data:
    - secretKey: HOME_ASSISTANT_USERNAME
      remoteRef:
        key: "f405049d-fa46-4097-8993-b40a009f8677" #gitleaks:allow #HOME_ASSISTANT_USERNAME
    - secretKey: HOME_ASSISTANT_PASSWORD
      remoteRef:
        key: "faa6454a-223f-4f52-9d45-b40a009fa2cb" #gitleaks:allow #HOME_ASSISTANT_PASSWORD
    - secretKey: S3_ACCESS_KEY
      remoteRef:
        key: "e00e1e38-ae37-479a-8b46-b409016331eb" #gitleaks:allow #S3_ACCESS_KEY
    - secretKey: S3_SECRET_KEY
      remoteRef:
        key: "4d5a418c-82ed-4b8e-bfbf-b40901634ea4" #gitleaks:allow #S3_SECRET_KEY
