name: ""
imageName: ""
instances: 1
storage:
  size: 1Gi
# # bootstrap:
# #   recovery:
# #     source: <cluster-name>-backup
# # externalClusters:
# #   - name: <cluster-name>-backup
# #     plugin:
# #       name: barman-cloud.cloudnative-pg.io
# #       parameters:
# #         barmanObjectName: <name>-objectstore
monitoring:
  enablePodMonitor: true
# retentionPolicy: "10d"
# objectStore:
#   destinationPath: "s3://bucket/cnpg/<name>"
#   endpointURL: <secret:s3_endpoint>
#   s3Credentials:
#     accessKeyId:
#       name: <app>-secrets
#       key: S3_ACCESS_KEY_ID
#     secretAccessKey:
#       name: <app>-secrets
#       key: S3_ACCESS_SECRET_KEY
# scheduledBackups:
#   - name: <name>-cnpg-backup
#     spec:
#       immediate: true
#       schedule: "5 0 0 * * *"
#       backupOwnerReference: self
