apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cluster-secrets
  namespace: argocd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  refreshInterval: 1h
  target:
    name: cluster-secrets
    creationPolicy: Owner
  data:
    - secretKey: private-domain
      remoteRef:
        key: "ce4d5e10-c9b7-4ed8-a519-b40901579a80" #gitleaks:allow #CLUSTER_SECRET_PRIVATE_DOMAIN
    - secretKey: s3_endpoint
      remoteRef:
        key: "8d2e328e-088f-42b6-baeb-b409015814eb" #gitleaks:allow #CLUSTER_SECRET_S3_ENDPOINT
    - secretKey: email
      remoteRef:
        key: "a76af954-ab75-40d6-9796-b409015857b3" #gitleaks:allow #CLUSTER_SECRET_CERT_MANAGER_EMAIL
    - secretKey: encryption-key
      remoteRef:
        key: "f406c9a4-a2ea-4da3-b2f8-b4090158ae57" #gitleaks:allow #CLUSTER_SECRET_N8N_ENCRYPTION_KEY
    - secretKey: discord_botid
      remoteRef:
        key: "f4f7ced4-2b39-4916-b1e7-b4090158da48" #gitleaks:allow #CLUSTER_SECRET_BOTKUBE_DISCORD_BOTID
    - secretKey: discord_token
      remoteRef:
        key: "f0e61e4a-473e-461f-897c-b4090158f933" #gitleaks:allow #CLUSTER_SECRET_BOTKUBE_DISCORD_TOKEN
    - secretKey: discord_channel
      remoteRef:
        key: "4d206666-9484-43aa-bc56-b409015955a7" #gitleaks:allow #CLUSTER_SECRET_BOTKUBE_DISCORD_CHANNEL
    - secretKey: ops
      remoteRef:
        key: "ef32a853-6918-450b-a030-b40901597a83" #gitleaks:allow #CLUSTER_SECRET_MINECRAFT_OPS
    - secretKey: whitelistUsers
      remoteRef:
        key: "bbbffb49-ed00-4bf0-ab0d-b4090159930c" #gitleaks:allow #CLUSTER_SECRET_MINECRAFT_WHITELIST_USERS
    - secretKey: world-password
      remoteRef:
        key: "bd5fcf7e-2644-42b3-b55a-b4090159b6cb" #gitleaks:allow #CLUSTER_SECRET_VINTAGESTORY_WORLD_PASSWORD
