apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: private-repo-creds
  namespace: argocd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  refreshInterval: 1h
  target:
    name: private-repo-creds
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      data:
        password: "{{ `{{ .PASSWORD }}` }}"
        type: "{{ `{{ .TYPE }}` }}"
        url: "{{ `{{ .URL }}` }}"
        username: "{{ `{{ .USERNAME }}` }}"
  data:
    - secretKey: TYPE
      remoteRef:
        key: "ebe306f4-ec6c-4c50-8048-b40a00992177" #gitleaks:allow #ARGOCD_PRIVATE_REPO_TYPE
    - secretKey: URL
      remoteRef:
        key: "132b2735-b75a-46f9-990b-b40a009935fc" #gitleaks:allow #ARGOCD_PRIVATE_REPO_URL
    - secretKey: USERNAME
      remoteRef:
        key: "c07a3879-62ef-4b0a-a6a3-b40a0099515d" #gitleaks:allow #ARGOCD_PRIVATE_REPO_USERNAME
    - secretKey: PASSWORD
      remoteRef:
        key: "2e3dedaa-274b-46fc-92f2-b40a00997609" #gitleaks:allow #ARGOCD_PRIVATE_REPO_PASSWORD
