app-template:
  defaultPodOptions:
    securityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
  controllers:
    main:
      replicas: 1
      strategy: Recreate
      containers:
        main:
          image:
            repository: koenkk/zigbee2mqtt
            tag: 2.14.1@sha256:fef0de769dcd04c27b3a6d277b61046eb96284bdd4198dcb1687c3a01b3020f3
          envFrom:
            - secretRef:
                name: zigbee2mqtt-secret
          env:
            TZ: Europe/Warsaw
          resources:
            requests:
              cpu: 20m
              memory: 128Mi
            limits:
              memory: 512Mi
  service:
    main:
      controller: main
      ports:
        http:
          port: 8080
  route:
    main:
      annotations:
        external-dns.alpha.kubernetes.io/controller: dns-controller
      parentRefs:
        - name: envoy-internal
          namespace: envoy-gateway
          sectionName: https
      hostnames:
        - z2m.<secret:private-domain>
      rules:
        - backendRefs:
            - identifier: main
  persistence:
    data:
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      globalMounts:
        - path: /app/data
