vernemq:
  replicaCount: 2
  service:
    mqtt:
      enabled: true
      port: 1883
  serviceMonitor:
    create: true
  pdb:
    enabled: true
    minAvailable: 1
  rbac:
    create: true
    serviceAccount:
      create: true
  persistentVolume:
    enabled: true
    accessModes:
      - ReadWriteMany
    size: 5Gi
    storageClass: ceph-filesystem
  resources:
    requests:
      memory: 1Gi
      cpu: 150m
    limits:
      memory: 1500Mi
      cpu: 500m
  additionalEnv:
    - name: DOCKER_VERNEMQ_ACCEPT_EULA
      value: "yes"
  envFrom:
    - secretRef:
        name: vernemq-users
