ollama:
  ollama:
    models:
      pull:
        - deepcoder:14b
        - qwen3.5:9b
        - gemma4:26b
        - nomic-embed-text
  extraEnv:
    - name: OLLAMA_KV_CACHE_TYPE
      value: "q4_0"
    - name: OLLAMA_NUM_PARALLEL
      value: "1"
    - name: OLLAMA_NUM_GPU
      value: "-1"
    - name: OLLAMA_FLASH_ATTENTION
      value: "1"
    - name: OLLAMA_CONTEXT_LENGTH
      value: "16384"
    - name: OLLAMA_VULKAN
      value: "1"
  service:
    type: ClusterIP
  ingress:
    enabled: false
  persistentVolume:
    enabled: true
    size: "40Gi"
  resources:
    limits:
      gpu.intel.com/i915: 1
      memory: 16Gi
    requests:
      gpu.intel.com/i915: 1
      cpu: 100m
      memory: 8Gi
