open-webui:
  ollama:
    enabled: false
  ingress:
    enabled: false
  route:
    enabled: true
    annotations:
      external-dns.alpha.kubernetes.io/controller: dns-controller
    parentRefs:
      - name: envoy-internal
        namespace: envoy-gateway
        sectionName: https
    hostnames:
      - chat.<secret:private-domain>
  image:
    repository: ghcr.io/open-webui/open-webui
    tag: "v0.8.10@sha256:ee057955040ce91e3e787e4b7978c9c23e828972c68d01d787ed40f9a307df9f"
    pullPolicy: "IfNotPresent"
  resources:
    requests:
      memory: 1100Mi
      cpu: 300m
    limits:
      memory: 2Gi
      cpu: "1"
  websocket:
    enabled: false
