open-webui:
  ollama:
    enabled: false
  ingress:
    enabled: true
    class: "traefik"
    host: chat.<secret:private-domain>
    tls: false
  image:
    repository: ghcr.io/open-webui/open-webui
    tag: "v0.8.7@sha256:8d74f073c7bfa494e374705e0aed326bc9dbb737e3ce0160533529a97957c19a"
    pullPolicy: "IfNotPresent"
  websocket:
    enabled: false
