namespace: nextcloud
image:
  repository: onlyoffice/documentserver
  tag: 9.0.0
port: 80
jwt:
  secretName: onlyoffice-jwt-secret
  secretKey: JWT_SECRET
database:
  host: onlyofficedb-cnpg-rw
  port: 5432
  name: app
  existingSecret:
    name: onlyofficedb-cnpg-app
    usernameKey: username
    passwordKey: password
storage:
  storageClass: ceph-block
  size: 5Gi
resources:
  requests:
    cpu: 500m
    memory: 2Gi
  limits:
    cpu: "2"
    memory: 4Gi
