namespace: nextcloud
image:
  repository: onlyoffice/documentserver
  tag: 9.0.0
port: 80
jwt:
  secretName: onlyoffice-jwt-secret
  secretKey: JWT_SECRET
storage:
  storageClass: ceph-block
  size: 5Gi
resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi
