apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speaches-models
  namespace: llm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.stt.storage }}
