apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-s3-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  refreshInterval: 1h
  target:
    name: keycloakdb-secrets
    creationPolicy: Owner
  data:
    - secretKey: S3_ACCESS_KEY_ID
      remoteRef:
        key: "e00e1e38-ae37-479a-8b46-b409016331eb" #gitleaks:allow #S3_ACCESS_KEY
    - secretKey: S3_ACCESS_SECRET_KEY
      remoteRef:
        key: "4d5a418c-82ed-4b8e-bfbf-b40901634ea4" #gitleaks:allow #S3_SECRET_KEY
